[package]
name = "greeting"
version = "0.1.0"
authors = ["lizhihong <lizhihong@buckyos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
